### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [codealchemist/concha#1]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by codealchemist** [comment]
Hi @Drulac!
Cool template engine implementation!

I tried it using something like this:
```
const compile = require('template-literal')

app.engine('js', (options, data, cb) => {
    const template = fs.readFileSync(options, 'utf8')
    const render = compile(template)
    const output = render(data)
    cb(output)
  })
```

It might be cool if you also provide a method like that with `template-literal` ;)
In my particular case I'll stay with EJS because the template file is more readable that way.
I'm already using template literals I'd need to escape on the template for it to work.
Also, I only have one variable and one template being parsed with EJS, not too bad.

But hey, thanks anyway for the recommendation!
And good job with `template-literal`!

Cheers!
